### ISSUE TITLE
How to close the prompt

### ISSUE THREAD

**Issue by axin0452** [NotTooManyItems/StepUp#11]
How to turn off [stepup]enabled
When playing bungee's server, you will be prompted every time you switch the world

**Comment by NotTooManyItems** [comment]
It's been added in the version for 1.17.1. Both start message and update messages can now be disabled.
Add the two lines under "# Configuration File".
Leave the #'s for backwards compatibility with versions older than 1.13. The config will break if you don't.
```
# display_start_message=0
# display_update_message=0
```
