### ISSUE TITLE
fast converting from 1.16.1 to 1.16.3 [Beta?]

### ISSUE THREAD

**Issue by markygnlg** [NotTooManyItems/StepUp#12]
Hi, I love this mod & saw your comment when asked "Is the mod abandoned?"

In reply to VL4DST3R: Posted Oct 7, 2020 #137
 No, I have other projects and work I'm juggling.

So I thought you'd might like to know that if you add the line:
license="All rights reserved"
... works when under the line --> loaderVersion="[32,)"

& change:
versionRange="[1.16.1]"
in the [[dependencies.stepup]] section to 1.16.3 then it will work for mc1.16.3 Forge 34.1.15. I've found that this works with many older mods (including when a newer forge is required which crashes my game).

Thanks for this great mod!
EDIT: these edits are for mods.toml in META-INF folder, but I'm sure you already knew.
EDIT2: BTW, I don't know programming/compiling/etc; these edits are a simple unzip jar, edit txt file, save, re-zip, rename to jar, replace original jar.

**Comment by gamax92** [comment]
The correct license is `license="LGPL v2.1"` btw as stated in LICENSE.txt

**Comment by markygnlg** [comment]
Oh, I didn't check other files in the jar. I use the steps that I posted on curseforge which includes checking the curseforge info that's displayed in the top right hand side of the page, ie.:
 
About Project ... Report
Project ID ... 239236
Created ... Dec 29, 2015
Updated ... Jun 28, 2020
Total Downloads ... 1,521,539
License ... All Rights Rese...

I'm no programmer so thx for the new info.
Take care,
M.

**Comment by markygnlg** [comment]
I just realised that the 'LICENSE.txt' is in github but not in the jar file that is on curseforge. As I am no programmer I'm not sure what you meant by you post - so to clarify: from my understanding the LGPL is almost identical to a GPL but not inclusive to libraries &/or mc Forge requirements that are/might used by your mod.

Can I ask you simply, can I upload a link to curseforge (I do not know how to use github) so that your StepUp mod is able to work on 1.16.3 after editing the mods.toml file (which would involve me finding some sort of file server) or would you rather take care of it yourself? I'm only asking coz your mod rox.

**Comment by gamax92** [comment]
I'm not the author, NotTooManyItems is
