### ISSUE TITLE
Growing number of mods break stepup

### ISSUE THREAD

**Issue by SiliconAshes** [NotTooManyItems/StepUp#15]
I realize, depending on the implementation in other mods, it may not be possible/feasible to fix this from within StepUp, but various mods prevent StepUp from functioning.  I am aware of Artifacts-1.16.5-2.9.0 and later, as well as previously reported, Environmental (Environmental 1.16.5 - 1.0.0).

I have filed a bug report with Artifacts (#96), but wanted to note it here as well.

Testing:
Install clean Minecraft 16.5 instance.
Install Forge (tested various, but 36.1.25)
Install Artifacts-1.16.5-2.9.2
Install StepUp-1.16.4-0.2.0

Create a new world (such as seed: New World), enter, and enable StepUp.
Verify it is functioning, 
equip Running Shoes from Artifacts
See that StepUp no longer functions.

**Comment by NotTooManyItems** [comment]
I can't fix this.
The two mods fight over the variable that controls the stepping up. And since you said it works until you put the shoes on, that means the dev of the other mod thought it through to not spam the value change when you don't have the shoes on. Very considerate of them.

**Comment by SiliconAshes** [comment]
That's OK.  I figured it was something like you describe, and the authors of, I believe now both, mods have at this point corrected the problem on their end.  I think there may be others, but I don't use them.

   Thank you very much for looking into this, and for the mod itself.  It may be a small mod, but I like it a lot.

**Comment by stickybeard** [comment]
another mod that is incompatible is https://www.curseforge.com/minecraft/mc-mods/enchants. I have tried with their step up enchantment enabled and disabled to no avail.  I have submitted an issue on their page.
