### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by KenyMylankca** [NotTooManyItems/StepUp#3]
I have the latest version of StepUp (1.0.2 on 1.12.2) but it still warns me in the game that there is an update. I can't disable the update check in configs too. Please fix both. Thanks!

**Comment by NotTooManyItems** [comment]
I can't replicate the version checking error on the latest version of stepup for 1.12.2.

**Comment by KenyMylankca** [comment]
can you at least add a config to disable the update checker please? i want to disable it. thanks!
