### ISSUE TITLE
Crashes when loaded on a server

### ISSUE THREAD

**Issue by NielsPilgaard** [NotTooManyItems/StepUp#6]
`StepUp-1.15.2-0.1.0` crashes when loaded on a server, here's the crash report:
https://gist.github.com/NillerMedDild/76cfd25c0a3edb1c08d8e25f0b0778ec

**Comment by NotTooManyItems** [comment]
Is this something that effects you a lot? Or can you go without placing StepUp into your server mod folder? StepUp is meant to be client-side only but I have had cases in the past where someone used the same mod folder for both client and server. I'm wondering how important it is for me to get this fixed. It requires a rewrite of how I handle client and server proxy.

**Comment by NielsPilgaard** [comment]
It affects me a lot sadly - I've removed StepUp from my modpacks because of it :/

I build server files automatically, and for some reason I have been unable to remove StepUp from the server files using my normal approach. So keeping StepUp would mean reverting to manually releasing updates.

**Comment by NotTooManyItems** [comment]
New version is up.

**Comment by NielsPilgaard** [comment]
Cool, thank you :D
