### ISSUE TITLE
Disabling StepUp disables PneumaticCraft Boots' Step Assist Ability

### ISSUE THREAD

**Issue by NielsPilgaard** [NotTooManyItems/StepUp#7]
Disabling the StepUp mod through the keybinding, negates the Step Assist ability from PneumaticCraft's Pneumatic Boots. 

It's not a big issue, but it can potentially cause some confusion for players who haven't used StepUp, but want to use Step Assist from Pneumatic Boots.

**Comment by NotTooManyItems** [comment]
Yes. Any other mod that modifies the value of stepHeight will conflict. I'm not sure if there is much I can do about it.

**Comment by NielsPilgaard** [comment]
Does the StepUp: Disabled setting set stepHeight, or does it just not increase it?

**Comment by NotTooManyItems** [comment]
Disable StepUp sets stepHeight to 0.6 . Which stops you from stepping up a block.

**Comment by NotTooManyItems** [comment]
`if (player.isCrouching()) {
            player.stepHeight = .6f;
        } else if (autoJumpState == 0 && player.stepHeight >= 1.0f) { //All Disabled
        	player.stepHeight = .6f;
        } else if (autoJumpState == 1 && player.stepHeight < 1.0f) { //StepUp Enabled
            player.stepHeight = 1.25f;
        } else if (autoJumpState == 2 && player.stepHeight >= 1.0f) { //Minecraft Enabled
            player.stepHeight = .6f;
        }`

**Comment by NotTooManyItems** [comment]
```
if (player.isCrouching()) {
    player.stepHeight = .6f;
} else if (autoJumpState == 0 && player.stepHeight >= 1.0f) { //All Disabled
    player.stepHeight = .6f;
} else if (autoJumpState == 1 && player.stepHeight < 1.0f) { //StepUp Enabled
    player.stepHeight = 1.25f;
} else if (autoJumpState == 2 && player.stepHeight >= 1.0f) { //Minecraft Enabled
    player.stepHeight = .6f;
}
```

**Comment by NielsPilgaard** [comment]
Couldn't you simply not alter it when all is disabled?

**Comment by NotTooManyItems** [comment]
I had it like that before. But other mods were disabling it constantly and I was getting issue reports for that. So to stop that I made it check and change it every tick. Going back to that other way will stop it from working with the other mods I changed it to this way for.

**Comment by NielsPilgaard** [comment]
Alright fair enough, thank you for your time :)

**Comment by NotTooManyItems** [comment]
I may actually be able to do something about this.

**Comment by NotTooManyItems** [comment]
New Version should address this.
I wasn't able to test to make sure it works, because I know nothing about the PneumaticCraft mod so I couldn't get the boots working. But I've modified the code to not constantly change the stepHeight value after "StepUp is Disable". It will do it once then wait until the hotkey is pressed to change the value again.

**Comment by NielsPilgaard** [comment]
Good approach, I'll test it and let you know :)

**Comment by NotTooManyItems** [comment]
Did this change the effect?

**Comment by NielsPilgaard** [comment]
I'm afraid it didn't help, atleast not in 1.15.2

**Comment by NotTooManyItems** [comment]
If the boots are worn when you have stepup enabled, and then you disable StepUp, the boots effect would also be disabled (they both effect the same stepHeight variable). And if the modder didn't program the boots to keep changing the stepHeight value when the boots are on, then you will be stuck with the stepHeight being .6 or step assist disabled. Pretty much.
And this wouldn't be my problem anymore, it would be the modder of the boots who needs to have their mod continuously check if the stepHeight is at the correct number and change it if it isn't on every client tick.

Experiment: Try disabling stepup in minecraft and then put the boots on. The boots should change the stepHeight value if it's done after stepup has been disabled.
If you've disabled stepup in minecraft and then put the boots on after, and still cannot walk up a block. Let me know and I'll look back at my source and see what's up.

**Comment by NielsPilgaard** [comment]
> Experiment: Try disabling stepup in minecraft and then put the boots on. The boots should change the stepHeight value if it's done after stepup has been disabled.
If you've disabled stepup in minecraft and then put the boots on after, and still cannot walk up a block. Let me know and I'll look back at my source and see what's up.

That's how I tested it :)

**Comment by NotTooManyItems** [comment]
Took the last few hours to look through my code and TeamPneumatic pnc-repressurized source code. And I'm not really seeing where the issue is that stops it from working now.

It appears Pneumatic mod should be setting stepHeight every playerTick as long as there is a armor pressure in the boots.
And I've verified that StepUp only calls to disable once when the hotkey is pressed.

I'm not sure where to go with this. There aren't any other mods in the mod pack that you are aware of that effect stepHeight variable or claims to have a step assist effect?

**Comment by NielsPilgaard** [comment]
Alright, thanks for taking the extra time to investigate. 

Botania's Soujorners Sash also has step assist, but works fine with StepUp disabled.

**Comment by NotTooManyItems** [comment]
Do those two mods step assist work together well without stepup mod loaded into minecraft? Maybe if you load up minecraft without StepUp and put on boots and belt, then take off the belt we will see if the boots are actually changing stepHeight every playerTick or not. As taking the belt off should make stepHeight normal again. But if the boots call every tick then stepHeight will be changed back to step assist value.

I hope that all makes sense.

**Comment by NielsPilgaard** [comment]
This is the bit of code that handles PneumaticCraft Step Assist: https://github.com/TeamPneumatic/pnc-repressurized/blob/3ebf81d101e1b9d79ea3be19519cb53229b70894/src/main/java/me/desht/pneumaticcraft/common/pneumatic_armor/CommonArmorHandler.java#L253

It seems I was wrong, it does now work after your changes - I tested it incorrectly last time, sorry about that.
