### ISSUE TITLE
[1.14.4] StepUp Incorrectly stating an update is available

### ISSUE THREAD

**Issue by NielsPilgaard** [NotTooManyItems/StepUp#8]
StepUp-1.14.4-0.2.1 says there's an update available, eventhough there isn't - I'm guessing it thinks the 1.15.2 version is an update.

**Comment by NotTooManyItems** [comment]
This issue should be fixed in the version I just released.

**Comment by NielsPilgaard** [comment]
The same thing happens between 1.15 and 1.16 now.

**Comment by NotTooManyItems** [comment]
Couldn't get it to show me the update message in 1.16 but when I loaded up 1.15 it was there.

I checked the update files I have hosted on pastebin and noticed 1.15 was off for some reason.  I have no idea why, it's like it reverted to the last version of the pastebin text I had a few months back. 

I changed it to what it should be and now I don't receive the update message.
